export const path = {
  login: "login",
  register: "register",
  dashboard: "dashboard",
  admin: "admin",
  user: "user",
  company: "company",
  job: "job",
  post: "post",
  cv: "cv",
  role: "role",
  permission: "permission",
  category: "category",
  home: "home",
  tour: "tour",
};
